name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --workspace --all-targets --all-features
      - run: cargo check --workspace --all-targets --no-default-features
      - run: cargo test --workspace --all-features
      - run: cargo test --doc --workspace --all-features
      - run: cargo test --examples --workspace --all-features

  doc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --all-features --no-deps

  markdown:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: DavidAnson/markdownlint-cli2-action@v21
        with:
          globs: "README.md docs/**/*.md"

  package:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo package --workspace

  dependency-policy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit,cargo-hack,cargo-machete,cargo-minimal-versions
      - run: cargo audit
      - run: cargo machete
      - run: cargo minimal-versions check --direct --workspace --all-targets --all-features
